/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/register': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a user and return access token
         * @description Register a user and return an access token
         */
        post: operations['registerUser'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/login': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh access token
         * @description Refresh access token
         */
        get: operations['refreshAccessToken'];
        put?: never;
        /**
         * Returns access token
         * @description Login
         */
        post: operations['login'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/products/search': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns products
         * @description Returns the products matching the query
         */
        get: operations['searchProducts'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/products/categories': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List product categories
         * @description Returns the distinct product categories
         */
        get: operations['listCategories'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/products/{productId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find product by ID
         * @description Returns the details of the product with the given id
         */
        get: operations['getProductById'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/reviews/{productId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find reviews by product ID
         * @description Returns the reviews and ratings of the product with the given id
         */
        get: operations['getReviewsByProductId'];
        put?: never;
        /**
         * Create a review
         * @description Add a review for a product (requires authentication)
         */
        post: operations['createReview'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/cart': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create cart
         * @description Create a new empty cart
         */
        post: operations['createCart'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/cart/{cartId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cart
         * @description Get a cart by id
         */
        get: operations['getCart'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/cart/{cartId}/items': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add cart item
         * @description Add an item to the cart (increments quantity if already present)
         */
        post: operations['addCartItem'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/cart/{cartId}/items/{productId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update cart item
         * @description Set the quantity of a cart item (0 removes it)
         */
        put: operations['updateCartItem'];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/orders': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders
         * @description List the authenticated user's orders
         */
        get: operations['listOrders'];
        put?: never;
        /**
         * Create order
         * @description Create an order from a cart (snapshots prices, empties the cart)
         */
        post: operations['createOrder'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/orders/{orderId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order
         * @description Get an order by id
         */
        get: operations['getOrder'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/orders/{orderId}/payment': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay order
         * @description Pay for an order (NEW -> PROCESSING). Requires a Bearer token.
         */
        post: operations['payOrder'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/orders/{orderId}/cancel': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel order
         * @description Cancel an order, allowed only while it has not shipped. Requires a Bearer token.
         */
        post: operations['cancelOrder'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/me': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin check
         * @description Returns 200 if the caller is an admin (used to gate admin UI). Requires a Bearer token.
         */
        get: operations['adminCheck'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/products': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create product
         * @description Create a product. Requires an admin Bearer token.
         */
        post: operations['createProduct'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/products/{productId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update product
         * @description Update a product. Requires an admin Bearer token.
         */
        put: operations['updateProduct'];
        post?: never;
        /**
         * Delete product
         * @description Delete a product. Requires an admin Bearer token.
         */
        delete: operations['deleteProduct'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/users/{userId}/block': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Block user
         * @description Block a user. Requires an admin Bearer token.
         */
        post: operations['blockUser'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/users/{userId}/unblock': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unblock user
         * @description Unblock a user. Requires an admin Bearer token.
         */
        post: operations['unblockUser'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/notifications': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications
         * @description List the authenticated user's notifications (newest first). Requires a Bearer token.
         */
        get: operations['listNotifications'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/notifications/read-all': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark all notifications read
         * @description Mark all the authenticated user's notifications as read. Requires a Bearer token.
         */
        post: operations['markAllNotificationsRead'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/notifications/{notificationId}/read': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark notification read
         * @description Mark one of the authenticated user's notifications as read. Requires a Bearer token.
         */
        post: operations['markNotificationRead'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/orders': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all orders
         * @description List every order (admin order management). Requires an admin Bearer token.
         */
        get: operations['listAllOrders'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/orders/{orderId}/ship': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ship order
         * @description Mark an order as shipped (PROCESSING -> SHIPPED), recording the tracking number, carrier and ETA. Requires an admin Bearer token.
         */
        post: operations['shipOrder'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/orders/{orderId}/deliver': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deliver order
         * @description Mark a shipped order as delivered (SHIPPED -> DELIVERED). Requires an admin Bearer token.
         */
        post: operations['deliverOrder'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @example john_doe@example.com */
            username: string;
            /** @example secret */
            password: string;
        };
        RegisterRequest: {
            /** @example john_doe@example.com */
            emailAddress: string;
            /** @example secret */
            password: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /** @example 100-0001 */
            postalCode?: string;
            /** @example 1-1 Chiyoda, Chiyoda-ku, Tokyo */
            address?: string;
        };
        ProductInput: {
            /**
             * @description Must be non-empty (validated server-side -> 422).
             * @example Banana
             */
            productName: string;
            /** @example fruit */
            productCategory?: string;
            /**
             * Format: int32
             * @description Must be >= 0 (validated server-side -> 422).
             * @example 200
             */
            priceJpy: number;
            /** @example /combo_examples/banana.png */
            productImageUrl?: string;
        };
        Product: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /** @example Banana */
            productName: string;
            /** @example fruit */
            productCategory?: string;
            /**
             * Format: int32
             * @example 200
             */
            priceJpy: number;
            /** @example https://example.com/images/banana.png */
            productImageUrl?: string;
        };
        ProductList: {
            products: components['schemas']['Product'][];
            /**
             * Format: int32
             * @example 0
             */
            pageNumber: number;
        };
        Review: {
            /** @example Great product, would buy again. */
            content: string;
            /**
             * Format: int32
             * @example 5
             */
            rating: number;
        };
        CreateReview: {
            /** @example Great product, would buy again. */
            content: string;
            /**
             * Format: int32
             * @example 5
             */
            rating: number;
        };
        CartItem: {
            /** Format: int64 */
            productId: number;
            productName: string;
            /** Format: int32 */
            unitPriceJpy: number;
            /** Format: int32 */
            quantity: number;
            /** Format: int32 */
            lineTotalJpy: number;
        };
        Cart: {
            /** Format: int64 */
            id: number;
            items: components['schemas']['CartItem'][];
            /** Format: int32 */
            totalJpy: number;
        };
        AddCartItem: {
            /** Format: int64 */
            productId: number;
            /**
             * Format: int32
             * @example 1
             */
            quantity: number;
        };
        UpdateCartItem: {
            /**
             * Format: int32
             * @example 2
             */
            quantity: number;
        };
        CreateOrder: {
            /** Format: int64 */
            cartId: number;
            /** @example 1-1 Chiyoda, Chiyoda-ku, Tokyo */
            shippingAddress: string;
        };
        PaymentRequest: {
            /**
             * @description Payment method. One of card, bank_transfer, cod.
             * @example card
             * @enum {string}
             */
            method: 'card' | 'bank_transfer' | 'cod';
            /**
             * @description Card number for the `card` method; ignored for bank_transfer / cod. Required (non-empty) when method is `card`.
             * @example 4242 4242 4242 4242
             */
            details?: string;
        };
        OrderItem: {
            /** Format: int64 */
            productId: number;
            productName: string;
            /** Format: int32 */
            unitPriceJpy: number;
            /** Format: int32 */
            quantity: number;
            /** Format: int32 */
            lineTotalJpy: number;
        };
        Order: {
            /** Format: int64 */
            id: number;
            items: components['schemas']['OrderItem'][];
            /** Format: int32 */
            totalJpy: number;
            shippingAddress: string;
            /** @example NEW */
            status: string;
            /** Format: date */
            orderDate?: string;
            /**
             * @description Carrier tracking number, set once the order ships.
             * @example 1Z999AA10123456784
             */
            trackingNumber?: string;
            /**
             * @description Shipping carrier, set once the order ships.
             * @example Yamato
             */
            carrier?: string;
            /**
             * Format: date
             * @description Date the order was marked SHIPPED.
             */
            shippedDate?: string;
            /**
             * Format: date
             * @description Estimated delivery date (ETA), set once the order ships.
             */
            estimatedDeliveryDate?: string;
        };
        ShipOrder: {
            /** @example 1Z999AA10123456784 */
            trackingNumber: string;
            /** @example Yamato */
            carrier: string;
            /**
             * Format: date
             * @description Estimated delivery date (ETA).
             * @example 2026-07-04
             */
            estimatedDeliveryDate?: string;
        };
        Notification: {
            /** Format: int64 */
            id: number;
            /**
             * @description One of ORDER_PLACED, PAID, SHIPPED, DELIVERED, CANCELLED.
             * @example SHIPPED
             */
            notificationType: string;
            /** @example Order */
            message: string;
            /** @example false */
            read: boolean;
            /**
             * Format: int64
             * @description The order this notification is about, when applicable.
             */
            orderId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['RegisterRequest'];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': string;
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid registration payload */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': string;
                };
            };
            /** @description Invalid or missing token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['LoginRequest'];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': string;
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchProducts: {
        parameters: {
            query?: {
                /** @description Free-text match against the product name or category */
                query?: string;
                /** @description Filter to an exact product category */
                category?: string;
                /** @description Zero-based page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ProductList'];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': string[];
                };
            };
        };
    };
    getProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the product to fetch */
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Product'];
                };
            };
            /** @description Invalid ID supplied */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReviewsByProductId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the product to fetch reviews for */
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The product's reviews (an empty list if it has none) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Review'][];
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the product to review */
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CreateReview'];
            };
        };
        responses: {
            /** @description The created review */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Review'];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid review (rating must be 1-5, content required) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Cart'];
                };
            };
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Cart'];
                };
            };
            /** @description Cart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['AddCartItem'];
            };
        };
        responses: {
            /** @description The updated cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Cart'];
                };
            };
            /** @description Cart or product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid quantity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: number;
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['UpdateCartItem'];
            };
        };
        responses: {
            /** @description The updated cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Cart'];
                };
            };
            /** @description Cart or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid quantity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Order'][];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CreateOrder'];
            };
        };
        responses: {
            /** @description The created order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Order'];
                };
            };
            /** @description Cart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cart is empty or request invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Order'];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['PaymentRequest'];
            };
        };
        responses: {
            /** @description The paid order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Order'];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Order is not payable (e.g. already paid) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid payment payload */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cancelled order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Order'];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Order can no longer be cancelled (already shipped) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller is an admin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ProductInput'];
            };
        };
        responses: {
            /** @description The created product */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Product'];
                };
            };
            /** @description Invalid product payload */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ProductInput'];
            };
        };
        responses: {
            /** @description The updated product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Product'];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid product payload */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product is referenced by orders/reviews and can't be deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    blockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User blocked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admins cannot be blocked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unblockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User unblocked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Notification'][];
                };
            };
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All notifications marked read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification marked read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Notification not found (or not owned by the caller) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAllOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Order'][];
                };
            };
        };
    };
    shipOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ShipOrder'];
            };
        };
        responses: {
            /** @description The shipped order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Order'];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Order is not in a shippable state (must be PROCESSING) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid ship payload */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deliverOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The delivered order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Order'];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Order is not in a deliverable state (must be SHIPPED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
